// ClassicMode — the untimed weekday screen. Extracted verbatim from main.tsx (the main.tsx split); it was
// already a module-level sibling of App taking everything through props, so nothing about its
// behaviour changes by living here.
import { useEffect, useState } from 'react'
import type { ModeProps, GenDate, FmtDate } from './modeTypes.js'
import {
  useButtonFlash,
  useStatsHideToggles,
  engineFresh,
  useResetStatsConfirm,
  useMountedDataId,
  readParkedHistory,
  restoredEngine,
  useParkedHistory,
  useSaveStatsOnRegen,
} from './modeHooks.js'
import { useSettingsCloseEffect } from '../components/useSettingsCloseEffect.js'
import { RESET_STATS_BTN_CLASS } from '../components/controlClasses.js'
import WeekdayAnswer from '../components/WeekdayAnswer.jsx'
import StatPanel from '../components/StatPanel.jsx'
import ConfirmModal from '../components/ConfirmModal.jsx'
import CardNumber from '../components/CardNumber.jsx'
import OverrideButton from '../components/OverrideButton.jsx'
import { MethodBreakdownSection } from '../components/MethodBreakdown.jsx'
import { useModePrefs } from '../store/modePrefs.js'
import { useProgress } from '../store/progress.js'
import { useGameEngine } from '../engine/useGameEngine.js'
import { creditsLiveCard } from '../engine/gameReducer.js'
import { useBackButton } from '../components/overlayStack.js'

// ============================================================
// ClassicMode — the Classic game mode, on the shared engine (mode-untangle Step 1c).
//
// Self-contained + always-mounted (display:none when inactive), exactly like AoxMode:
// it owns ALL of Classic's state via useGameEngine (the pure reducer) plus its own
// display toggles (timing/scoring hide, the timing-desync two-tap) and the transient
// button flash. App no longer renders Classic inline — it just mounts <ClassicMode/>
// and passes the settings down (like it does for AoxMode). This is the first mode
// carved out of App's fused rendering; Flash/Blitz/Deduction follow onto the same engine.
// ============================================================
function ClassicMode({
  visible,
  genDate,
  minY,
  maxY,
  useJulian,
  saveStats,
  dateFormat,
  randomFormat,
  inputStyle = 'buttons',
  dotRotation = 'standard',
  leapChance,
  janFebChance,
  julianChance,
  fmtDate,
  settingsOpen,
  onFreshChange,
}: ModeProps & { genDate: GenDate; fmtDate: FmtDate }) {
  const timingOff = useModePrefs((s) => s.classicTimingOff),
    setTimingOff = useModePrefs((s) => s.setClassicTimingOff) // persisted; timing hidden by default (feeds the engine)
  const scoringOff = useModePrefs((s) => s.classicScoringOff),
    setScoringOff = useModePrefs((s) => s.setClassicScoringOff) // persisted; scoring shown by default
  // Lifetime stats persist across reloads (Stage D1): hydrate from saved progress on mount,
  // then mirror every stats change back to the store.
  // …and the HISTORY behind them is kept for the browsing session (store/sessionHistory): what this
  // screen last parked — before a reload, a preset switch, a guest's interlude — comes back as the
  // engine's first state, read once, keyed by the stats copy this screen is mounted on; and the
  // question that was waiting comes back or is regenerated by modeHooks' live-question rule.
  const dataId = useMountedDataId()
  // The date settings a question is drawn under on this screen — ONE list, read by the park (as the
  // settings the waiting question belongs to) and by the settings-close regen below.
  const dateSettings = [
    randomFormat,
    dateFormat,
    leapChance,
    janFebChance,
    julianChance,
    minY,
    maxY,
  ]
  const dateConfig = dateSettings.join('|')
  const [parked] = useState(() => readParkedHistory(dataId, 'classic', useJulian))
  const eng = useGameEngine({
    label: 'classic',
    genDate,
    minY,
    maxY,
    useJulian,
    saveStats,
    timingOff,
    inPlay: () => visible,
    getInitialStats: () => useProgress.getState().stats.classic,
    getInitialState: () =>
      restoredEngine(parked, {
        timeRecorded: !timingOff && saveStats,
        config: dateConfig,
        newDate: () => genDate(minY, maxY),
      }),
  })
  const { state, correct, overrideAvail, overridden } = eng
  useParkedHistory(dataId, 'classic', state, visible, { config: dateConfig }, settingsOpen ?? false)
  // Android Back closes the Show-Codes panel of the ACTIVE mode. Gated on `visible` so only
  // the on-screen mode registers (the others are mounted-but-hidden); `eng` is the active engine
  // (for Deduction it's the current silo), so this is one line per mode. See components/overlayStack.
  useBackButton(visible && state.calcOpen, () => eng.showCodes(false), 'codes')
  const setModeStats = useProgress((s) => s.setModeStats)
  useEffect(() => {
    setModeStats('classic', state.stats)
  }, [state.stats, setModeStats])
  const { flash, setFlashWithTimeout } = useButtonFlash() // green/red answer pulse
  // Hideable stats chrome (show/hide toggles + the "Enable and Reset Stats?" desync confirm + the
  // 6-box stats strip), shared with Flash/Deduction via useStatsHideToggles.
  const { statsArr, enableResetOpen, confirmEnableReset, closeEnableReset } = useStatsHideToggles({
    eng,
    timed: [eng],
    saveStats,
    visible,
    timingOff,
    setTimingOff,
    scoringOff,
    setScoringOff,
  })
  const optionsDisabled = state.locked || state.calcOpen || state.calcPenaltyActive
  const revealDisabled =
    (state.locked && state.revealed) || state.calcOpen || state.calcPenaltyActive

  const onAnswer = (i: number) => {
    setFlashWithTimeout({ type: i === correct ? 'good' : 'bad', idx: i })
    eng.answer(i)
  }
  // The one Override ⇄ Undo press (round 23). A press that CREDITS the live question pulses green
  // on the correct button (the engine's creditsLiveCard — one rule for every mode). Everything else
  // is the engine's alone: Classic keeps no state of its own that an Override changes, in either
  // direction.
  const onOverride = () => {
    if (creditsLiveCard(eng.overridePlan)) setFlashWithTimeout({ type: 'good', idx: correct })
    eng.override()
  }

  // regenDecisionFor (App's popover effect, Classic slice): a format / leap / Jan-Feb /
  // Julian-chance / year-range change regens an UNANSWERED live date; a useJulian toggle
  // keeps it — an untouched date's answer and codes follow the setting as it stands, and one
  // already judged keeps the calendar it was judged in (the engine's calendarOf). REGEN_DATE
  // no-ops on a burned or browsed date, so we just fire it on the relevant changes.
  // Defer the live-date regen to the ⚙ popover CLOSE — batched, no per-keystroke timer churn.
  useSettingsCloseEffect(settingsOpen ?? false, dateSettings, () => eng.regenDate())
  // …and so does Save Stats coming back on while this mode's timing is shown (modeHooks).
  useSaveStatsOnRegen(settingsOpen ?? false, saveStats, timingOff, () => eng.regenDate())
  // Freshness — engine state at launch default + Classic's own toggle/flash fields. Reported up
  // via onFreshChange so App's isFullyReset (Full Reset dim/lock) accounts for Classic.
  const classicIsFresh =
    engineFresh(state) &&
    timingOff === true &&
    scoringOff === false &&
    enableResetOpen === false &&
    flash === null
  // The Reset Stats confirmation popup.
  const {
    confirmOpen: resetStatsOpen,
    onResetTap,
    closeConfirm: closeResetStats,
    confirmReset: confirmResetStats,
  } = useResetStatsConfirm(eng.resetStats, !engineFresh(state), visible)
  useEffect(() => {
    onFreshChange?.(classicIsFresh)
  }, [classicIsFresh, onFreshChange])
  const date = state.date
  return (
    <div style={{ display: visible ? 'block' : 'none' }}>
      {/* dimmed = Save Stats off = nothing is being recorded: the whole strip dims and every value
          reads '—'. A group you turned off yourself renders BLANK instead, from `off` inside
          statsArr — two facts, two flags. See the three-signal note in components/StatPanel. */}
      <StatPanel stats={statsArr} dimmed={!saveStats} />
      <div className="mt-3">
        {/* Reset Stats — a static caption now; the confirmation is the shared ConfirmModal below
            (round 21 replaced the two-tap in-place arm). The `S` shortcut routes through this
            same onClick, so it opens the popup too. */}
        <button type="button" data-key="S" className={RESET_STATS_BTN_CLASS} onClick={onResetTap}>
          Reset Stats
        </button>
      </div>
      <ConfirmModal
        open={resetStatsOpen}
        onCancel={closeResetStats}
        onConfirm={confirmResetStats}
        title="Reset Stats?"
        body="Clears this mode's stats and all-time bests for the preset you are on. The other modes keep theirs, and no other preset is touched."
        confirmLabel="Reset Stats"
        id="reset-stats-classic"
      />
      <ConfirmModal
        open={enableResetOpen}
        onCancel={closeEnableReset}
        onConfirm={confirmEnableReset}
        title="Enable and Reset Stats?"
        body="The timer readouts were hidden while this mode's stats changed, so turning them back on has to reset this mode's stats for the preset you are on. The other modes keep theirs, and no other preset is touched."
        confirmLabel="Enable and Reset Stats"
        id="enable-reset-stats-classic"
      />
      <div className="mt-5">
        <div className="mt-4 rounded-2xl panel p-4">
          <div className="text-center relative">
            <CardNumber state={state} show={state.backDepth > 0} />
            <div className="text-3xl font-bold">{fmtDate(date.y, date.m, date.d, date._fmt)}</div>
          </div>
          <WeekdayAnswer
            key={state.gridEpoch}
            inputStyle={inputStyle}
            dotRotation={dotRotation}
            persistBtns={state.persistBtns}
            flash={flash}
            optionsDisabled={optionsDisabled}
            onPick={onAnswer}
          />
        </div>
        <div className="mt-4 rounded-2xl panel p-3 space-y-3">
          <div className="grid grid-cols-4 gap-2">
            <button
              type="button"
              data-key="N"
              className="col-span-1 px-3 py-2 rounded-xl border surface-button text-sm font-medium"
              onClick={() => eng.doNew()}
            >
              New
            </button>
            <div className="col-span-1 flex gap-1">
              <button
                type="button"
                data-key="ArrowLeft"
                className={`flex-1 px-1 py-2 rounded-xl border surface-button text-sm font-medium flex items-center justify-center ${state.stack.length === 0 ? 'opacity-60 pointer-events-none' : ''}`}
                onClick={eng.back}
              >
                <span style={{ position: 'relative', top: '-1.5px' }}>&lt;</span>
              </button>
              <button
                type="button"
                data-key="ArrowRight"
                className={`flex-1 px-1 py-2 rounded-xl border surface-button text-sm font-medium flex items-center justify-center ${state.forwardStack.length === 0 ? 'opacity-60 pointer-events-none' : ''}`}
                onClick={eng.forward}
              >
                <span style={{ position: 'relative', top: '-1.5px' }}>&gt;</span>
              </button>
            </div>
            <button
              type="button"
              data-key="R"
              className={`col-span-1 px-3 py-2 rounded-xl border surface-button text-sm font-medium text-center ${revealDisabled ? 'opacity-60 pointer-events-none' : ''}`}
              onClick={eng.reveal}
            >
              Reveal
            </button>
            <OverrideButton avail={overrideAvail} overridden={overridden} onToggle={onOverride} />
          </div>
          <MethodBreakdownSection
            date={date}
            open={state.calcOpen}
            onOpenChange={(open) => eng.showCodes(open)}
            className=""
            contentClassName="mt-2 rounded-2xl thin px-4 pt-[3px] pb-1.5"
            useJulian={eng.julian}
            displayedFormat={date?._fmt || dateFormat}
          />
        </div>
      </div>
    </div>
  )
}

export default ClassicMode
